config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users

  resources(:users)
  resources(:registrations, only: %i[new create])

  root "root#index"

  resources(:meals) do
    get :search, on: :collection
    get :autocomplete, on: :collection
    resources :cookings
  end

  resources(:cookings)
  resources(:tags)
  resources(:stats)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  belongs_to :meal
  validates :cooked_at, presence: true
  validates_uniqueness_of :meal_id, :scope => :cooked_at
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :cookings, dependent: :destroy
  validates :title, presence: true
  acts_as_taggable_on :tags

  scope :top10, -> {
    select("meals.id, title, count(cookings.id) AS cookings_count").
    joins(:cookings).
    group("meals.id").
    order("cookings_count DESC").
    limit(10)
  }
end

app/models/user.rb
require 'domain_validator'

class User < ApplicationRecord
  passwordless_with :email
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_with DomainValidator
  has_many( :sessions, class_name: 'Passwordless::Session', foreign_key: 'authenticatable_id' )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Passwordless::ControllerHelpers
  helper_method :current_user

  private

  def current_user
    @current_user ||= authenticate_by_session(User) || upgrade_passwordless_cookie(User)
  end

  def authenticate_user!
    return if current_user
    save_passwordless_redirect_location!(User)

    flash[:error] = 'Dafür musst Du angemeldet sein.'
    redirect_to '/users/sign_in'
  end
end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params.include?(:week_of)
      @week_of = Time.parse(params[:week_of]).beginning_of_week.to_date
    else
      @week_of = Time.now.beginning_of_week.to_date
    end

    full_week = @week_of.beginning_of_week..@week_of.end_of_week
    cookings_of_week = Cooking.includes(:meal).where(cooked_at: full_week).to_a

    @cookings_for_week = full_week.inject(Hash.new) do |cookings, date|
      cookings[date] = cookings_of_week.select{|c| c.cooked_at == date}
      cookings
    end
  end

  def new
    @cooking = Cooking.new(cooked_at: params[:cooked_at])
  end

  def create
    @meal = Meal.find(params[:meal_id])
    @cooking = @meal.cookings.create(cooking_params)
    redirect_to meal_path(@meal)
  end

  def destroy
    @meal = Meal.find(params[:meal_id])
    @cooking = @meal.cookings.find(params[:id])
    @cooking.destroy
    redirect_to meal_path(@meal), status: 303
  end

  private

  def cooking_params
    params.require(:cooking).permit(:cooked_at, :meal_id)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!

  def index
    @meals = Meal.includes(:cookings).order('cookings.cooked_at DESC')
    @tags = Meal.tag_counts_on(:tags)
  end

  def search
    if params[:meal_id].present? && Meal.exists?(params[:meal_id]) # from autocomplete
      redirect_to meal_path(params[:meal_id])
    end

    @query = params[:query].strip
    title_matcher = Meal.arel_table[:title]
    @meals = Meal.where(title_matcher.matches("%#{ActiveRecord::Base::sanitize_sql_like(@query)}%"))
  end

  def autocomplete
    @query = params[:q].strip
    title_matcher = Meal.arel_table[:title]
    @meals = Meal.where(title_matcher.matches("%#{ActiveRecord::Base::sanitize_sql_like(@query)}%"))
    render 'autocomplete', layout: nil
  end

  def show
    @meal = Meal.find(params[:id])
    @tags = @meal.tag_counts_on(:tags)
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to @meal
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      redirect_to @meal
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def meal_params
    params.require(:meal).permit(:title, :notes, :tag_list)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:email))

    if @user.save
      sign_in(@user)
      redirect_to(root_path)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    redirect_to :cookings if current_user
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
     @top10 = Meal.top10
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Meal.tag_counts_on(:tags)
  end

  def show
    if params[:id].present?
      @tag = params[:id]
      @meals = Meal.tagged_with(@tag)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:notice] = 'Benutzer wurde gelöscht.'
    redirect_to(users_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_search.html.erb
<div data-controller="autocomplete" data-autocomplete-url-value="/meals/autocomplete" data-autocomplete-submit-on-enter-value="true">
<%= form_with url: "/meals/search", method: :get do |form| %>
  <%= form.text_field :query,
      value: @query,
      class: 'form-control',
      placeholder: "Suchen...",
      'data-autocomplete-target' => "input",
      autofocus: true
  %>
  <input id="autocomplete-target" type="hidden" name="meal_id" data-autocomplete-target="hidden" onchange="this.form.submit()"/>
  <ul data-autocomplete-target="results" class="autocomplete-results list-group"/>
<% end %>
</div>

app/views/cookings/_cooking.html.erb
<li>
  <%= I18n.l(cooking.cooked_at) %>
  <%= link_to "❌", [cooking.meal, cooking], data: {
                turbo_method: :delete,
                turbo_confirm: "Eintrag für den #{I18n.l(cooking.cooked_at)} wirklich löschen?"
              } %>
</li>

app/views/cookings/_nav.html.erb
<nav style="text-align: center;">
  <%= link_to '<<', cookings_path(week_of: week_of.last_week), style: 'margin-right: 1em;' %>
  <%= link_to 'Heute', cookings_path(week_of: Time.now.monday.to_date) %>
  <%= link_to '>>', cookings_path(week_of: week_of.next_week), style: 'margin-left: 1em;' %>
</nav>

app/views/cookings/index.html.erb
<%= render 'nav', week_of: @week_of %>

<h1>Woche vom <%= I18n.l(@week_of) %></h1>

<% @cookings_for_week.reverse_each do |date, cookings| %>
  <b><%= I18n.l(date) %></b>
  <small>(<%= link_to 'Ergänzen', new_cooking_path(cooked_at: date) %>)</small>

  <p>
  <% cookings.each do |cooking| %>
    <%= link_to cooking.meal.title, cooking.meal %><br/>
  <% end %>
  </p>
<% end %>

<%= render 'nav', week_of: @week_of %>

app/views/cookings/new.html.erb
<h1>gegessen am <%= I18n.l(@cooking.cooked_at) %></h1>

<%= form_with model: [ @cooking ] do |form| %>
  <p>
    <%= form.hidden_field :cooked_at %>
    <%= render 'search' %>
    <%= form.submit 'Eintragen' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>
<body>
  <header>
    <nav>
      <%= link_to "Home", main_app.root_path %>
      <%= link_to "Essen", main_app.meals_path %>
      <%= link_to "Tags", main_app.tags_path %>
      <%= link_to "Statistik", main_app.stats_path %>
      <%= link_to "Benutzer", main_app.users_path %>
      <% if current_user %>
        <%= link_to "Abmelden", users.sign_out_path %>
      <% else %>
        <%= link_to "Anmelden", users.sign_in_path %>
      <% end %>
    </nav>

    <h1>Meal Tracker</h1>
    <p>Wann haben wir <i>das</i> zuletzt gegessen?</p>
  </header>

  <main>
    <% flash.each do |kind, msg| %>
      <%= tag.div(class: kind) { msg } %>
    <% end %>

    <%= yield %>
  </main>

  <footer>
    <% if current_user %>
      <p>Du bist angemeldet als <%= current_user.email %></p>
    <% end %>
    <p>Steffen Uhlig, 2022</p>
  </footer>
</body>
</html>

app/views/meals/_form.html.erb
<%= form_with model: @meal do |form| %>
  <div>
    <%= form.label 'Titel' %><br>
    <%= form.text_field :title, autofocus: true %>
    <% @meal.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label 'Notizen' %><br>
    <%= form.text_area :notes %>
    <% @meal.errors.full_messages_for(:notes).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :tag_list, "Tags" %><br>
    <%= form.text_field :tag_list, value: @meal.tag_list, placeholder: 'z.B. pizza pasta fleisch'
    %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meals/_meals.html.erb
<ul>
  <% @meals.each do |meal| %>
    <li>
      <%= link_to meal.title, meal %>
      <% if last_cooked = meal.cookings.order(cooked_at: :desc).first %>
        (zuletzt gegessen am <%= I18n.l last_cooked.cooked_at %>)
      <% end %>
    </li>
  <% end %>
</ul>

app/views/meals/autocomplete.erb
<% @meals.each do |meal| %>
  <li class="list-group-item" role="option" data-autocomplete-value="<%= meal.id %>" data-autocomplete-label="<%= meal.title %>">
    <%= meal.title %>
  </li>
<% end %>

app/views/meals/edit.html.erb
<h1>Essen bearbeiten</h1>

<%= render "form", meal: @meal %>

app/views/meals/index.html.erb
<h1>Essen</h1>

<%= render 'search' %>

<p><%= link_to "Hinzufügen...", new_meal_path %></p>

<%= render 'meals' %>

<p><%= link_to "Hinzufügen...", new_meal_path %></p>

app/views/meals/new.html.erb
<h1>Neues Essen</h1>

<%= render "form", meal: @meal %>

app/views/meals/search.html.erb
<h1><%= @meals.size %> Ergebnisse für "<%= @query %>"</h1>

<%= render 'meals' %>

<p><%= link_to "Hinzufügen...", new_meal_path %></p>

app/views/meals/show.html.erb
<h1><%= @meal.title %></h1>

<section>
  <h2>Zuletzt gegessen am</h2>
  <p>
  <ul>
    <%= render @meal.cookings %>
  </ul>

  <%= form_with model: [ @meal, @meal.cookings.build ] do |form| %>
    <p>
      <%= form.date_field :cooked_at, value: DateTime.now.to_date %>

      <%# TODO Does not show errors %>
      <% @meal.errors.full_messages_for(:cooked_at).each do |message| %>
        <div><%= message %></div>
      <% end %>

      <%= form.submit 'Anlegen' %>
    </p>
  <% end %>
  </p>
</section>

<section>
  <h2>Notizen</h2>
  <p><%= @meal.notes %></p>
</section>

<section>
  <h2>Tags</h2>
  <p><%= render 'tags/cloud' %></p>
</section>

<section>
  <h2>Aktionen</h2>
  <ul>
    <li><%= link_to "Bearbeiten", edit_meal_path(@meal) %></li>
    <li><%= link_to "Löschen", meal_path(@meal), data: {
                      turbo_method: :delete,
                      turbo_confirm: "\"#{@meal.title}\" wirklich löschen?"
                    } %></li>
  </ul>
</section>

app/views/meals/tag.erb
<h1>Essen getagged mit <code><%= @tag %></code></h1>

<section>
  <%= render 'meals' %>
</section>

app/views/meals/tags.erb
<h1>Alle Tags</h1>

<section>
<%= render 'tag_cloud' %>
</section>

app/views/root/index.html.erb
Hier kannst Du tracken, was wir wann gegessen haben.

app/views/stats/index.html.erb
<h1>Top 10</h1>

<table>
<tr>
  <th>Platz</th>
  <th>Essen</th>
  <th>gegessen</th>
  <th>zuletzt</th>
</tr>

<% @top10.each.with_index do |meal, place| %>
<tr>
  <td><%= place + 1 %></td>
  <td><%= link_to meal.title, meal %></td>
  <td><%= meal.cookings_count %> mal</td>
  <td><%= I18n.l(meal.cookings.order(cooked_at: :desc).first.cooked_at) %></td>
</tr>
<% end %>

</table>

app/views/tags/_cloud.erb
<% tag_cloud(@tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class| %>
  <%= link_to tag, tag_path(tag.name), class: css_class %>
<% end %>

app/views/tags/index.erb
<h1>Alle Tags</h1>

<section>
<%= render 'cloud' %>
</section>

app/views/tags/show.erb
<h1>Essen getagged mit <code><%= @tag %></code></h1>

<section>
  <%= render 'meals/meals' %>
</section>

app/views/users/index.html.erb
<h1>Benutzer</h1>

<table>
  <thead>
    <tr>
      <th>eMail</th>
      <th>zuletzt angemeldet</th>
      <th>Aktionen</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= I18n.l user.sessions.where("claimed_at not NULL").order(:updated_at).last.updated_at %></td>
        <td>
          <% if user == current_user %>
            (aktiv)
          <% else %>
          <%= link_to 'Löschen', user_path(user), method: :delete, data: {
                      turbo_method: :delete,
                      turbo_confirm: "\"#{user.email}\" wirklich löschen?"
              }
          %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neu registrieren', new_registration_path %>